In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("assignment 4.xlsx")
df.head()

weight  price
0       2     35
1       4     60
2       5     20
3       3     50
4       6     50

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   weight  7 non-null      int64
 1   price   7 non-null      int64
dtypes: int64(2)
memory usage: 244.0 bytes


In [4]:
df.head()

weight  price
0       2     35
1       4     60
2       5     20
3       3     50
4       6     50

In [5]:
x = df['weight']
y = df['price']

In [6]:
import numpy as np

In [7]:
mean_x = np.mean(x)
mean_y = np.mean(y)

In [8]:
#calculate deviations
dev_x = x - mean_x
dev_y = y - mean_y

In [9]:
coefficient = np.sum(dev_x * dev_y) / np.sum(dev_x**2) 
coefficient

2.620967741935484

In [10]:
intercept = mean_y - (coefficient * mean_x)

In [11]:
pred_y = (coefficient * 2000) + intercept
pred_y

5277.096774193548

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
reg = LinearRegression()

In [14]:
reg.fit(df[['weight']] , df[['price']]) #training

LinearRegression()

In [15]:
reg.coef_

array([[2.62096774]])

In [16]:
reg.intercept_

array([35.16129032])

In [17]:
df.head()

weight  price
0       2     35
1       4     60
2       5     20
3       3     50
4       6     50

In [18]:
m = reg.coef_
c = reg.intercept_
m*2000 + c

array([[5277.09677419]])

In [19]:
reg.predict([[35]])

C:\Users\nuret\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[126.89516129]])

In [20]:
df['predicted_price'] = reg.predict(df[['weight']])

In [21]:
df.head()

weight  price  predicted_price
0       2     35        40.403226
1       4     60        45.645161
2       5     20        48.266129
3       3     50        43.024194
4       6     50        50.887097

In [22]:
df['residiuls'] = df['price'] - df['predicted_price']

In [23]:
df.head()

weight  price  predicted_price  residiuls
0       2     35        40.403226  -5.403226
1       4     60        45.645161  14.354839
2       5     20        48.266129 -28.266129
3       3     50        43.024194   6.975806
4       6     50        50.887097  -0.887097

In [24]:
#mse
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(df['price'], df['predicted_price'])

In [25]:
mse

167.30990783410135

In [26]:
#mae
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(df['price'], df['predicted_price'])

In [27]:
mae

9.87327188940092

In [29]:
import pandas as pd

data = {'Weight': [2, 4, 5, 3, 6, 5, 7],
        'Price': [35, 60, 20, 50, 50, 55, 60]}

df = pd.DataFrame(data)

df['Total'] = df['Weight'] * df['Price']

excel_file_path = 'output_dataset.xlsx'

df.to_excel(excel_file_path, index=False)

print(f"Excel file '{excel_file_path}' has been created with the calculated 'Total' column.")


Excel file 'output_dataset.xlsx' has been created with the calculated 'Total' column.
